"""Plot OrbMol-v2 energies and fragment charges across the NcQEq spacing scan.

Run from the repository root:

    python examples/ncqeq/atcne-example/plot_ncqeq_scan.py

The first 24 atoms and the remaining atoms are evaluated with neutral (0, 0)
and ionic (+1, -1) regional charge constraints. The unconstrained OrbMol-v2
predictions are included as a comparison. Spacing values are generated by
translating the second fragment of a template structure so the fragment
centroid-to-centroid distance runs from 2.5 Å to 7.0 Å in 0.1 Å increments.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import NamedTuple

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch_sim as ts
from ase.io import read
from torch_sim.autobatching import BinningAutoBatcher

from orb_models.forcefield import pretrained
from orb_models.forcefield.inference.orb_torchsim import OrbTorchSimModel

N_FIRST_REGION = 24
DEFAULT_SPACING_START = 2.5
DEFAULT_SPACING_STOP = 10.0
DEFAULT_SPACING_STEP = 0.1
DEFAULT_TEMPLATE = Path(__file__).parent / "structures" / "spacing=2.5.xyz"


class CasePrediction(NamedTuple):
    energy: np.ndarray
    first_region_charge: np.ndarray
    second_region_charge: np.ndarray
    electrostatic_energy: np.ndarray


def _spacing_values(start: float, stop: float, step: float) -> list[float]:
    if step <= 0:
        raise ValueError("Spacing step must be positive.")
    n_steps = int(round((stop - start) / step))
    if n_steps < 0:
        raise ValueError("Spacing stop must be greater than or equal to spacing start.")
    if not np.isclose(start + n_steps * step, stop):
        raise ValueError("Spacing range must be divisible by spacing step.")
    return [float(round(start + i * step, 10)) for i in range(n_steps + 1)]


def _with_fragment_spacing(atoms, spacing: float):
    """Return a copy with the second fragment translated to the requested spacing."""
    if len(atoms) <= N_FIRST_REGION:
        raise ValueError(f"Template must contain more than {N_FIRST_REGION} atoms.")

    spaced_atoms = atoms.copy()
    positions = spaced_atoms.positions.copy()
    first_centroid = positions[:N_FIRST_REGION].mean(axis=0)
    second_centroid = positions[N_FIRST_REGION:].mean(axis=0)
    centroid_delta = second_centroid - first_centroid
    template_spacing = np.linalg.norm(centroid_delta)
    if template_spacing == 0:
        raise ValueError("Template fragment centroids must not overlap.")

    direction = centroid_delta / template_spacing
    desired_second_centroid = first_centroid + spacing * direction
    positions[N_FIRST_REGION:] += desired_second_centroid - second_centroid
    spaced_atoms.positions = positions
    return spaced_atoms


def _electronic_coupling(
    total_charge_energy: float,
    neutral_regional_energy: float,
    ionic_regional_energy: float,
) -> float:
    """Calculate V = sqrt((U - D0A0) * (U - D+A-)) in eV."""
    radicand = (total_charge_energy - neutral_regional_energy) * (
        total_charge_energy - ionic_regional_energy
    )
    return float(np.sqrt(radicand)) if radicand >= 0 else float("nan")


def _u1_energy(
    neutral_regional_energy: float,
    ionic_regional_energy: float,
    electronic_coupling: float,
) -> float:
    """Calculate U1 from the two regional energies and electronic coupling in eV."""
    return float(
        0.5
        * (
            neutral_regional_energy
            + ionic_regional_energy
            + np.sqrt(
                (neutral_regional_energy - ionic_regional_energy) ** 2 + 4 * electronic_coupling**2
            )
        )
    )


def _batched_sim_state(
    atoms_list,
    *,
    device: torch.device,
    dtype: torch.dtype,
    regional_charges: tuple[float, float] | None,
) -> ts.SimState:
    """Build a batched TorchSim state for one charge-constraint case."""
    n_systems = len(atoms_list)
    if n_systems == 0:
        raise ValueError("At least one structure is required.")

    n_atoms_per_system = [len(atoms) for atoms in atoms_list]
    if len(set(n_atoms_per_system)) != 1:
        raise ValueError("The NcQEq spacing sweep expects equal-sized systems.")
    n_atoms = n_atoms_per_system[0]
    if n_atoms <= N_FIRST_REGION:
        raise ValueError(f"Template must contain more than {N_FIRST_REGION} atoms.")

    positions = np.concatenate([atoms.positions for atoms in atoms_list])
    masses = np.concatenate([atoms.get_masses() for atoms in atoms_list])
    atomic_numbers = np.concatenate([atoms.numbers for atoms in atoms_list])
    system_idx = np.repeat(np.arange(n_systems), n_atoms)
    cell = np.tile(np.eye(3) * 100.0, (n_systems, 1, 1))

    kwargs = {}
    if regional_charges is not None:
        mask = np.concatenate(
            [np.array([0] * N_FIRST_REGION + [1] * (n_atoms - N_FIRST_REGION)) for _ in atoms_list]
        )
        kwargs["region_mask"] = torch.as_tensor(
            mask,
            dtype=torch.long,
            device=device,
        )
        kwargs["region_charges"] = torch.as_tensor(
            [regional_charges] * n_systems,
            dtype=dtype,
            device=device,
        )

    return ts.SimState(
        positions=torch.as_tensor(positions, dtype=dtype, device=device),
        masses=torch.as_tensor(masses, dtype=dtype, device=device),
        cell=torch.as_tensor(cell, dtype=dtype, device=device),
        pbc=torch.tensor([False, False, False], device=device),
        atomic_numbers=torch.as_tensor(atomic_numbers, dtype=torch.long, device=device),
        system_idx=torch.as_tensor(system_idx, dtype=torch.long, device=device),
        charge=torch.zeros(n_systems, dtype=dtype, device=device),
        spin=torch.ones(n_systems, dtype=dtype, device=device),
        **kwargs,
    )


def _static_autobatcher(calculator: OrbTorchSimModel) -> BinningAutoBatcher:
    """Use TorchSim autobatching without the slow CUDA memory-estimation pre-pass.

    Passing raw ``autobatcher=True`` makes TorchSim estimate the maximum safe
    batch size by repeatedly running the model on synthetic larger batches. For
    this OrbMol-v2 conservative model that pre-pass can dominate runtime and
    appears to hang before the progress bar starts. The example still uses
    TorchSim's static autobatching path, but provides an explicit memory scaler
    equivalent to 16 ATCNE systems per static batch.
    """
    return BinningAutoBatcher(
        model=calculator,
        memory_scales_with="n_atoms",
        max_memory_scaler=544.0,
    )


def _static_energy(results: dict[str, torch.Tensor]) -> torch.Tensor:
    if "potential_energy" in results:
        return results["potential_energy"]
    if "energy" in results:
        return results["energy"]
    if "free_energy" in results:
        return results["free_energy"]
    raise KeyError("TorchSim static did not return potential_energy, energy, or free_energy.")


def _energy(results: dict[str, torch.Tensor]) -> torch.Tensor:
    if "energy" in results:
        return results["energy"]
    if "free_energy" in results:
        return results["free_energy"]
    if "potential_energy" in results:
        return results["potential_energy"]
    raise KeyError("TorchSim Orb model did not return energy or free_energy.")


def _electrostatic_energy(results: dict[str, torch.Tensor]) -> torch.Tensor:
    if "coulomb_energy" not in results:
        raise KeyError("TorchSim Orb model did not return coulomb_energy.")
    return results["coulomb_energy"]


def _predict_static(
    atoms_list,
    *,
    calculator: OrbTorchSimModel,
    device: torch.device,
    dtype: torch.dtype,
    regional_charges: tuple[float, float] | None,
) -> CasePrediction:
    """Predict one charge case with torch_sim.static and TorchSim autobatching."""
    state = _batched_sim_state(
        atoms_list,
        device=device,
        dtype=dtype,
        regional_charges=regional_charges,
    )
    with torch.enable_grad():
        static_results = ts.static(
            state,
            calculator,
            autobatcher=_static_autobatcher(calculator),
            pbar=True,
        )

    energy = []
    electrostatic_energy = []
    first_region_charge = []
    second_region_charge = []
    for result in static_results:
        energy.append(float(_static_energy(result).detach().cpu().reshape(-1)[0]))
        electrostatic_energy.append(
            float(_electrostatic_energy(result).detach().cpu().reshape(-1)[0])
        )
        charges = result["latent_charges"].detach().cpu().squeeze(-1)
        first_region_charge.append(float(charges[:N_FIRST_REGION].sum()))
        second_region_charge.append(float(charges[N_FIRST_REGION:].sum()))

    return CasePrediction(
        energy=np.array(energy),
        first_region_charge=np.array(first_region_charge),
        second_region_charge=np.array(second_region_charge),
        electrostatic_energy=np.array(electrostatic_energy),
    )


def _cross_fragment_edge_counts(
    atoms_list,
    *,
    calculator: OrbTorchSimModel,
    device: torch.device,
    dtype: torch.dtype,
) -> np.ndarray:
    """Count directed graph edges that connect the two fragments for each spacing."""
    state = _batched_sim_state(
        atoms_list,
        device=device,
        dtype=dtype,
        regional_charges=None,
    )
    batch = calculator.atoms_adapter.from_torchsim_state(
        state,
        edge_method=calculator.edge_method,
        device=device,
        output_dtype=dtype,
    )

    senders = batch.senders.detach().cpu().numpy()
    receivers = batch.receivers.detach().cpu().numpy()
    n_atoms = len(atoms_list[0])
    counts = []
    for system_index in range(len(atoms_list)):
        atom_start = system_index * n_atoms
        atom_stop = atom_start + n_atoms
        in_system = (senders >= atom_start) & (senders < atom_stop)
        local_senders = senders[in_system] - atom_start
        local_receivers = receivers[in_system] - atom_start
        cross_edges = ((local_senders < N_FIRST_REGION) & (local_receivers >= N_FIRST_REGION)) | (
            (local_senders >= N_FIRST_REGION) & (local_receivers < N_FIRST_REGION)
        )
        counts.append(int(cross_edges.sum()))

    return np.array(counts, dtype=int)


def _write_csv(rows: list[dict[str, float]], path: Path) -> None:
    with path.open("w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=rows[0])
        writer.writeheader()
        writer.writerows(rows)


def _plot(rows: list[dict[str, float]], path: Path) -> None:
    spacing = np.array([row["spacing_angstrom"] for row in rows])
    unconstrained_energy = np.array([row["unconstrained_energy_ev"] for row in rows])
    constrained_energy = np.array([row["constrained_energy_ev"] for row in rows])
    ionic_constrained_energy = np.array([row["ionic_constrained_energy_ev"] for row in rows])
    u1_energy = np.array([row["u1_energy_ev"] for row in rows])
    energy_reference = unconstrained_energy[-1]
    unconstrained_energy -= energy_reference
    constrained_energy -= energy_reference
    ionic_constrained_energy -= energy_reference
    u1_energy -= energy_reference

    fig, axes = plt.subplots(4, 1, figsize=(7, 13), sharex=True, constrained_layout=True)
    axes[0].plot(spacing, unconstrained_energy, "o-", label="OrbMol-v2 total-charge constraint")
    axes[0].plot(spacing, constrained_energy, "o-", label="OrbMol-v2 regional constraints (0, 0)")
    axes[0].plot(
        spacing,
        ionic_constrained_energy,
        "o-",
        label="OrbMol-v2 regional constraints (+1, -1)",
    )
    axes[0].plot(spacing, u1_energy, "o-", label="U1")
    axes[0].set_ylabel("Relative energy (eV)")
    axes[0].legend()
    axes[0].grid(alpha=0.3)
    # axes[0].set_xlim(2.5, 5)

    axes[1].plot(
        spacing,
        [row["unconstrained_first_region_charge_e"] for row in rows],
        "o-",
        label="First 24 atoms, total-charge constraint",
    )
    axes[1].plot(
        spacing,
        [row["constrained_first_region_charge_e"] for row in rows],
        "o-",
        label="First 24 atoms, regional constraints (0, 0)",
    )
    axes[1].plot(
        spacing,
        [row["ionic_constrained_first_region_charge_e"] for row in rows],
        "o-",
        label="First 24 atoms, regional constraints (+1, -1)",
    )
    axes[1].axhline(0.0, color="black", linestyle="--", linewidth=1, label="Neutral target")
    axes[1].axhline(1.0, color="gray", linestyle="--", linewidth=1, label="Ionic target")
    axes[1].set_ylabel("First-region latent charge (e)")
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    axes[2].plot(
        spacing,
        [row["electronic_coupling_ev"] for row in rows],
        "o-",
        color="tab:purple",
    )
    axes[2].set_ylabel("Electronic coupling, V (eV)")
    axes[2].grid(alpha=0.3)

    axes[3].plot(spacing, [row["cross_fragment_edges"] for row in rows], "o-")
    axes[3].set_xlabel("Structure spacing (Å)")
    axes[3].set_ylabel("Cross-fragment directed edges")
    axes[3].grid(alpha=0.3)

    fig.savefig(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--spacing-start", type=float, default=DEFAULT_SPACING_START)
    parser.add_argument("--spacing-stop", type=float, default=DEFAULT_SPACING_STOP)
    parser.add_argument("--spacing-step", type=float, default=DEFAULT_SPACING_STEP)
    parser.add_argument(
        "--batch-size",
        type=int,
        default=None,
        help=argparse.SUPPRESS,
    )
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).parent)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = parser.parse_args()

    template_atoms = read(args.template)
    spacing_values = _spacing_values(
        args.spacing_start,
        args.spacing_stop,
        args.spacing_step,
    )
    atoms_list = [_with_fragment_spacing(template_atoms, spacing) for spacing in spacing_values]

    model, atoms_adapter = pretrained.orbmol_v2(
        device=args.device, compile=False, precision="float64"
    )
    calculator = OrbTorchSimModel(
        model,
        atoms_adapter,
        device=args.device,
        dtype=torch.get_default_dtype(),
    )
    device = calculator.device
    dtype = calculator.dtype or torch.get_default_dtype()

    unconstrained = _predict_static(
        atoms_list,
        calculator=calculator,
        device=device,
        dtype=dtype,
        regional_charges=None,
    )
    constrained = _predict_static(
        atoms_list,
        calculator=calculator,
        device=device,
        dtype=dtype,
        regional_charges=(0.0, 0.0),
    )
    ionic_constrained = _predict_static(
        atoms_list,
        calculator=calculator,
        device=device,
        dtype=dtype,
        regional_charges=(1.0, -1.0),
    )
    cross_fragment_edges = _cross_fragment_edge_counts(
        atoms_list,
        calculator=calculator,
        device=device,
        dtype=dtype,
    )

    rows = []
    for index, spacing in enumerate(spacing_values):
        electronic_coupling = _electronic_coupling(
            total_charge_energy=unconstrained.energy[index],
            neutral_regional_energy=constrained.energy[index],
            ionic_regional_energy=ionic_constrained.energy[index],
        )
        u1_energy = _u1_energy(
            neutral_regional_energy=constrained.energy[index],
            ionic_regional_energy=ionic_constrained.energy[index],
            electronic_coupling=electronic_coupling,
        )
        rows.append(
            {
                "spacing_angstrom": spacing,
                "unconstrained_energy_ev": unconstrained.energy[index],
                "constrained_energy_ev": constrained.energy[index],
                "ionic_constrained_energy_ev": ionic_constrained.energy[index],
                "unconstrained_electrostatic_energy_ev": unconstrained.electrostatic_energy[index],
                "constrained_electrostatic_energy_ev": constrained.electrostatic_energy[index],
                "ionic_constrained_electrostatic_energy_ev": (
                    ionic_constrained.electrostatic_energy[index]
                ),
                "unconstrained_first_region_charge_e": unconstrained.first_region_charge[index],
                "unconstrained_second_region_charge_e": unconstrained.second_region_charge[index],
                "constrained_first_region_charge_e": constrained.first_region_charge[index],
                "constrained_second_region_charge_e": constrained.second_region_charge[index],
                "ionic_constrained_first_region_charge_e": (
                    ionic_constrained.first_region_charge[index]
                ),
                "ionic_constrained_second_region_charge_e": (
                    ionic_constrained.second_region_charge[index]
                ),
                "electronic_coupling_ev": electronic_coupling,
                "u1_energy_ev": u1_energy,
                "cross_fragment_edges": cross_fragment_edges[index],
            }
        )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = args.output_dir / "ncqeq_spacing_scan.csv"
    edge_csv_path = args.output_dir / "ncqeq_cross_fragment_edges.csv"
    plot_path = args.output_dir / "ncqeq_spacing_scan.svg"
    _write_csv(rows, csv_path)
    _write_csv(
        [
            {
                "spacing_angstrom": row["spacing_angstrom"],
                "cross_fragment_edges": row["cross_fragment_edges"],
            }
            for row in rows
        ],
        edge_csv_path,
    )
    _plot(rows, plot_path)
    print(f"Wrote {csv_path}")
    print(f"Wrote {edge_csv_path}")
    print(f"Wrote {plot_path}")


if __name__ == "__main__":
    main()
